// Generated by CoffeeScript 1.12.7
(function() {
  var AES, k, questions, v;

  require('colors');

  AES = require("crypto-js/aes");

  console.log('\033[2J');

  console.log('\033[0;0H');

  console.log("AESCrypt".cyan + "\n");

  questions = {
    1: {
      name: 'operation',
      type: 'list',
      message: 'Operation',
      choices: ['Encrypt', 'Decrypt']
    },
    2: {
      name: 'message',
      type: 'input',
      message: 'Message',
      validate: function(input) {
        return input !== '';
      }
    },
    3: {
      name: 'pass',
      type: 'input',
      message: 'Passphrase',
      validate: function(input) {
        return input !== '';
      }
    }
  };

  require('inquirer').prompt((function() {
    var results;
    results = [];
    for (k in questions) {
      v = questions[k];
      results.push(v);
    }
    return results;
  })()).then(function(answers) {
    var output;
    output = function() {
      var hex;
      if (answers.operation === 'Encrypt') {
        return AES.encrypt(answers.message, answers.pass).toString().red;
      } else {
        hex = AES.decrypt(answers.message, answers.pass).toString();
        return require('buffer').Buffer.from(hex, "hex").toString().green;
      }
    };
    return console.log("\n" + output() + "\n");
  });

}).call(this);
